name: Deploy to GitHub Packages
run-name: ${{ github.actor }} is deploying to GitHub packages
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Test token
        run: echo ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build and deploy
        run: mvn -X deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
